export const USERS_LIST_INIT = '[USERS] USERS_LIST_INIT';
export const USERS_LIST_SUCCESS = '[USERS] USERS_LIST_SUCCESS';
export const USERS_LIST_ERROR = '[USERS] USERS_LIST_ERROR';
export const USERS_CREATE_INIT = '[USERS] USERS_CREATE_INIT';
export const USERS_CREATE_SUCCESS = '[USERS] USERS_CREATE_SUCCESS';
export const USERS_CREATE_ERROR = '[USERS] USERS_CREATE_ERROR';
